version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: painter_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/painter_booking
      JWT_SECRET: your-jwt-secret-key
      NODE_ENV: development
      PORT: 3001
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:


